version: "3.9"

services:
  api:
    build: .
    container_name: minimarket_api
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      DATABASE_URL: postgresql://postgres.rcxcfmkpsizivrgfzjtr:TU_PASSWORD@aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
      JWT_SECRET: 123456
    restart: always
